// Date: 3/22/2014 2:24:20 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.wolfoxgaming.technitool.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;

public class TechniToolModel extends ModelBase {
	// fields
	public ModelRenderer Core;
	public ModelRenderer ButtCrystalRight;
	public ModelRenderer ButtBack;
	public ModelRenderer ButtCrystalLeft;
	public ModelRenderer ButtTop;
	public ModelRenderer CrystalLeft;
	public ModelRenderer ButtRight;
	public ModelRenderer CrystalCenter;
	public ModelRenderer ButtLeft;
	public ModelRenderer CrystalLeft1;
	public ModelRenderer BarrelRightBottom;
	public ModelRenderer Core1;
	public ModelRenderer BarrelRightTop;
	public ModelRenderer BarrelLeftTop;
	public ModelRenderer BarrelLeftBottom;
	public ModelRenderer BarrelBase;
	public ModelRenderer BarrelRightMiddle;
	public ModelRenderer BarrelTop;
	public ModelRenderer BarrelLeftMiddle;

	public TechniToolModel() {
		textureWidth = 64;
		textureHeight = 32;

		Core = new ModelRenderer(this, 0, 0);
		Core.addBox(0F, 0F, 0F, 5, 1, 6);
		Core.setRotationPoint(-2F, 0F, 0F);
		Core.setTextureSize(64, 32);
		Core.mirror = true;
		setRotation(Core, 0F, 0F, 0F);
		ButtCrystalRight = new ModelRenderer(this, 0, 0);
		ButtCrystalRight.addBox(0F, 0F, 0F, 1, 3, 3);
		ButtCrystalRight.setRotationPoint(3F, -3F, 2F);
		ButtCrystalRight.setTextureSize(64, 32);
		ButtCrystalRight.mirror = true;
		setRotation(ButtCrystalRight, 0F, 0F, 0F);
		ButtBack = new ModelRenderer(this, 0, 0);
		ButtBack.addBox(0F, 0F, 0F, 3, 3, 1);
		ButtBack.setRotationPoint(-1F, -3F, 0F);
		ButtBack.setTextureSize(64, 32);
		ButtBack.mirror = true;
		setRotation(ButtBack, 0F, 0F, 0F);
		ButtCrystalLeft = new ModelRenderer(this, 0, 0);
		ButtCrystalLeft.addBox(0F, 0F, 0F, 1, 3, 3);
		ButtCrystalLeft.setRotationPoint(-3F, -3F, 2F);
		ButtCrystalLeft.setTextureSize(64, 32);
		ButtCrystalLeft.mirror = true;
		setRotation(ButtCrystalLeft, 0F, 0F, 0F);
		ButtTop = new ModelRenderer(this, 0, 0);
		ButtTop.addBox(0F, 0F, 0F, 5, 1, 7);
		ButtTop.setRotationPoint(-2F, -4F, 0F);
		ButtTop.setTextureSize(64, 32);
		ButtTop.mirror = true;
		setRotation(ButtTop, 0F, 0F, 0F);
		CrystalLeft = new ModelRenderer(this, 0, 0);
		CrystalLeft.addBox(0F, 0F, 0F, 1, 1, 1);
		CrystalLeft.setRotationPoint(1F, -5F, 3F);
		CrystalLeft.setTextureSize(64, 32);
		CrystalLeft.mirror = true;
		setRotation(CrystalLeft, 0F, 0F, 0F);
		ButtRight = new ModelRenderer(this, 0, 0);
		ButtRight.addBox(0F, 0F, 0F, 1, 3, 6);
		ButtRight.setRotationPoint(2F, -3F, 0F);
		ButtRight.setTextureSize(64, 32);
		ButtRight.mirror = true;
		setRotation(ButtRight, 0F, 0F, 0F);
		CrystalCenter = new ModelRenderer(this, 0, 0);
		CrystalCenter.addBox(0F, 0F, 0F, 1, 1, 3);
		CrystalCenter.setRotationPoint(0F, -5F, 2F);
		CrystalCenter.setTextureSize(64, 32);
		CrystalCenter.mirror = true;
		setRotation(CrystalCenter, 0F, 0F, 0F);
		ButtLeft = new ModelRenderer(this, 0, 0);
		ButtLeft.addBox(0F, 0F, 0F, 1, 3, 6);
		ButtLeft.setRotationPoint(-2F, -3F, 0F);
		ButtLeft.setTextureSize(64, 32);
		ButtLeft.mirror = true;
		setRotation(ButtLeft, 0F, 0F, 0F);
		CrystalLeft = new ModelRenderer(this, 0, 0);
		CrystalLeft.addBox(0F, 0F, 0F, 1, 1, 1);
		CrystalLeft.setRotationPoint(-1F, -5F, 3F);
		CrystalLeft.setTextureSize(64, 32);
		CrystalLeft.mirror = true;
		setRotation(CrystalLeft, 0F, 0F, 0F);
		BarrelRightBottom = new ModelRenderer(this, 0, 0);
		BarrelRightBottom.addBox(0F, 0F, 0F, 1, 1, 7);
		BarrelRightBottom.setRotationPoint(2F, -1F, 8F);
		BarrelRightBottom.setTextureSize(64, 32);
		BarrelRightBottom.mirror = true;
		setRotation(BarrelRightBottom, 0F, 0F, 0F);
		Core = new ModelRenderer(this, 0, 0);
		Core.addBox(0F, 0F, 0F, 3, 3, 12);
		Core.setRotationPoint(-1F, -3F, 1F);
		Core.setTextureSize(64, 32);
		Core.mirror = true;
		setRotation(Core, 0F, 0F, 0F);
		BarrelRightTop = new ModelRenderer(this, 0, 0);
		BarrelRightTop.addBox(0F, 0F, 0F, 1, 1, 7);
		BarrelRightTop.setRotationPoint(2F, -3F, 10F);
		BarrelRightTop.setTextureSize(64, 32);
		BarrelRightTop.mirror = true;
		setRotation(BarrelRightTop, 0F, 0F, 0F);
		BarrelLeftTop = new ModelRenderer(this, 0, 0);
		BarrelLeftTop.addBox(0F, 0F, 0F, 1, 1, 7);
		BarrelLeftTop.setRotationPoint(-2F, -3F, 10F);
		BarrelLeftTop.setTextureSize(64, 32);
		BarrelLeftTop.mirror = true;
		setRotation(BarrelLeftTop, 0F, 0F, 0F);
		BarrelLeftBottom = new ModelRenderer(this, 0, 0);
		BarrelLeftBottom.addBox(0F, 0F, 0F, 1, 1, 7);
		BarrelLeftBottom.setRotationPoint(-2F, -1F, 8F);
		BarrelLeftBottom.setTextureSize(64, 32);
		BarrelLeftBottom.mirror = true;
		setRotation(BarrelLeftBottom, 0F, 0F, 0F);
		BarrelBase = new ModelRenderer(this, 0, 0);
		BarrelBase.addBox(0F, 0F, 0F, 5, 1, 7);
		BarrelBase.setRotationPoint(-2F, 0F, 7F);
		BarrelBase.setTextureSize(64, 32);
		BarrelBase.mirror = true;
		setRotation(BarrelBase, 0F, 0F, 0F);
		BarrelRightMiddle = new ModelRenderer(this, 0, 0);
		BarrelRightMiddle.addBox(0F, 0F, 0F, 1, 1, 7);
		BarrelRightMiddle.setRotationPoint(2F, -2F, 9F);
		BarrelRightMiddle.setTextureSize(64, 32);
		BarrelRightMiddle.mirror = true;
		setRotation(BarrelRightMiddle, 0F, 0F, 0F);
		BarrelTop = new ModelRenderer(this, 0, 0);
		BarrelTop.addBox(0F, 0F, 0F, 5, 1, 8);
		BarrelTop.setRotationPoint(-2F, -4F, 10F);
		BarrelTop.setTextureSize(64, 32);
		BarrelTop.mirror = true;
		setRotation(BarrelTop, 0F, 0F, 0F);
		BarrelLeftMiddle = new ModelRenderer(this, 0, 0);
		BarrelLeftMiddle.addBox(0F, 0F, 0F, 1, 1, 7);
		BarrelLeftMiddle.setRotationPoint(-2F, -2F, 9F);
		BarrelLeftMiddle.setTextureSize(64, 32);
		BarrelLeftMiddle.mirror = true;
		setRotation(BarrelLeftMiddle, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Core.render(f5);
		ButtCrystalRight.render(f5);
		ButtBack.render(f5);
		ButtCrystalLeft.render(f5);
		ButtTop.render(f5);
		CrystalLeft.render(f5);
		ButtRight.render(f5);
		CrystalCenter.render(f5);
		ButtLeft.render(f5);
		CrystalLeft.render(f5);
		BarrelRightBottom.render(f5);
		Core.render(f5);
		BarrelRightTop.render(f5);
		BarrelLeftTop.render(f5);
		BarrelLeftBottom.render(f5);
		BarrelBase.render(f5);
		BarrelRightMiddle.render(f5);
		BarrelTop.render(f5);
		BarrelLeftMiddle.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity ent) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}
}
